version: '3.8'

services:
  nginx:
    container_name: nginx
    networks:
      - inception
    build: requirements/nginx
    depends_on:
      - wordpress
    env_file: .env
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    networks:
      - inception
    # image: mysql:5.7
    build: requirements/mariadb
    env_file: .env
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    networks:
      - inception
    # image: wordpress:latest
    build: requirements/wordpress
    depends_on:
      - mariadb
    env_file: .env
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: volume
      device: /home/fleitz/data/wordpress
      o: bind
  mariadb:
    name: mariadb
    driver_opts:
      type: volume
      device: /home/fleitz/data/mariadb
      o: bind

networks:
  inception:
